version: '3.1'
services:
  barrier_detection:
    image: barrier_detection
    build: .
    container_name: barrier_detection
    tty: true # persist on ports
    volumes:
      - .:/home/tensorflow
    networks:
      barrier_detection:
        ipv4_address: 172.06.0.9
networks:
  barrier_detection:
    ipam:
      config:
        - subnet: 172.06.0.0/16
          #docker-compose v3+ do not use ip_range
          ip_range: 192.168.0.1/24
